[2025-09-17T16:45:04.661+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-17T16:45:04.746+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T14:30:00+00:00 [queued]>
[2025-09-17T16:45:04.768+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T14:30:00+00:00 [queued]>
[2025-09-17T16:45:04.770+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-17T16:45:04.797+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-17 14:30:00+00:00
[2025-09-17T16:45:04.815+0200] {standard_task_runner.py:64} INFO - Started process 802 to run task
[2025-09-17T16:45:04.823+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-17T14:30:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpuilp5wnp']
[2025-09-17T16:45:04.828+0200] {standard_task_runner.py:91} INFO - Job 83: Subtask dbt_deps
[2025-09-17T16:45:04.967+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T14:30:00+00:00 [running]> on host 1621268d5064
[2025-09-17T16:45:05.708+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-17T14:30:00+00:00'
[2025-09-17T16:45:05.711+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-17T16:45:05.726+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-17T16:45:05.729+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-17T16:45:05.750+0200] {subprocess.py:86} INFO - Output:
[2025-09-17T16:45:08.477+0200] {subprocess.py:93} INFO - [0m14:45:08  Running with dbt=1.8.3
[2025-09-17T16:45:10.421+0200] {subprocess.py:93} INFO - [0m14:45:10  Installing dbt-labs/dbt_utils
[2025-09-17T16:45:21.621+0200] {subprocess.py:93} INFO - [0m14:45:21  Installed from version 1.3.1
[2025-09-17T16:45:21.629+0200] {subprocess.py:93} INFO - [0m14:45:21  Up to date!
[2025-09-17T16:45:24.054+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-17T16:45:24.066+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-17T16:45:24.331+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-17T14:30:00+00:00, execution_date=20250917T143000, start_date=20250917T144504, end_date=20250917T144524
[2025-09-17T16:45:25.211+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-17T16:45:25.279+0200] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-17T16:45:25.295+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
