[2025-09-15T20:01:04.493+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-15T20:01:04.542+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T17:45:00+00:00 [queued]>
[2025-09-15T20:01:04.551+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T17:45:00+00:00 [queued]>
[2025-09-15T20:01:04.552+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-15T20:01:04.566+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-15 17:45:00+00:00
[2025-09-15T20:01:04.573+0200] {standard_task_runner.py:64} INFO - Started process 387 to run task
[2025-09-15T20:01:04.579+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-15T17:45:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpuvo_0srx']
[2025-09-15T20:01:04.583+0200] {standard_task_runner.py:91} INFO - Job 11: Subtask dbt_deps
[2025-09-15T20:01:04.717+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T17:45:00+00:00 [running]> on host f51a750ef2c3
[2025-09-15T20:01:05.295+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T17:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T17:45:00+00:00'
[2025-09-15T20:01:05.297+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-15T20:01:05.319+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-15T20:01:05.322+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-15T20:01:05.342+0200] {subprocess.py:86} INFO - Output:
[2025-09-15T20:01:08.038+0200] {subprocess.py:93} INFO - [0m18:01:08  Running with dbt=1.8.3
[2025-09-15T20:01:09.034+0200] {subprocess.py:93} INFO - [0m18:01:09  Installing dbt-labs/dbt_utils
[2025-09-15T20:01:14.998+0200] {subprocess.py:93} INFO - [0m18:01:14  Installed from version 1.3.1
[2025-09-15T20:01:15.000+0200] {subprocess.py:93} INFO - [0m18:01:14  Up to date!
[2025-09-15T20:01:16.058+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-15T20:01:16.060+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-15T20:01:16.128+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-15T17:45:00+00:00, execution_date=20250915T174500, start_date=20250915T180104, end_date=20250915T180116
[2025-09-15T20:01:16.191+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-15T20:01:16.225+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-15T20:01:16.228+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
