[2025-09-16T00:58:16.393+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T00:58:16.493+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T22:30:00+00:00 [queued]>
[2025-09-16T00:58:16.515+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T22:30:00+00:00 [queued]>
[2025-09-16T00:58:16.516+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-16T00:58:16.545+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-15 22:30:00+00:00
[2025-09-16T00:58:16.552+0200] {standard_task_runner.py:64} INFO - Started process 230 to run task
[2025-09-16T00:58:16.557+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-15T22:30:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpn_d2awbg']
[2025-09-16T00:58:16.561+0200] {standard_task_runner.py:91} INFO - Job 5: Subtask dbt_deps
[2025-09-16T00:58:16.666+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T22:30:00+00:00 [running]> on host 1621268d5064
[2025-09-16T00:58:17.221+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T22:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T22:30:00+00:00'
[2025-09-16T00:58:17.223+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T00:58:17.243+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-16T00:58:17.245+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-16T00:58:17.261+0200] {subprocess.py:86} INFO - Output:
[2025-09-16T00:58:21.067+0200] {subprocess.py:93} INFO - [0m22:58:21  Running with dbt=1.8.3
[2025-09-16T00:58:22.754+0200] {subprocess.py:93} INFO - [0m22:58:22  Installing dbt-labs/dbt_utils
[2025-09-16T00:58:30.697+0200] {subprocess.py:93} INFO - [0m22:58:30  Installed from version 1.3.1
[2025-09-16T00:58:30.698+0200] {subprocess.py:93} INFO - [0m22:58:30  Up to date!
[2025-09-16T00:58:31.872+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-16T00:58:31.873+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T00:58:31.917+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-15T22:30:00+00:00, execution_date=20250915T223000, start_date=20250915T225816, end_date=20250915T225831
[2025-09-16T00:58:31.965+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-16T00:58:31.993+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-16T00:58:31.996+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
