[2025-09-17T19:30:06.309+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-17T19:30:06.363+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T17:15:00+00:00 [queued]>
[2025-09-17T19:30:06.376+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T17:15:00+00:00 [queued]>
[2025-09-17T19:30:06.377+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-17T19:30:06.394+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-17 17:15:00+00:00
[2025-09-17T19:30:06.405+0200] {standard_task_runner.py:64} INFO - Started process 464 to run task
[2025-09-17T19:30:06.411+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-17T17:15:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpyl531ok3']
[2025-09-17T19:30:06.416+0200] {standard_task_runner.py:91} INFO - Job 15: Subtask dbt_deps
[2025-09-17T19:30:06.533+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T17:15:00+00:00 [running]> on host cc1d85c9aa13
[2025-09-17T19:30:06.974+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T17:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-17T17:15:00+00:00'
[2025-09-17T19:30:06.975+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-17T19:30:06.997+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-17T19:30:06.999+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-17T19:30:07.019+0200] {subprocess.py:86} INFO - Output:
[2025-09-17T19:30:09.748+0200] {subprocess.py:93} INFO - [0m17:30:09  Running with dbt=1.8.3
[2025-09-17T19:30:11.712+0200] {subprocess.py:93} INFO - [0m17:30:11  Installing dbt-labs/dbt_utils
[2025-09-17T19:30:31.520+0200] {subprocess.py:93} INFO - [0m17:30:31  Installed from version 1.3.1
[2025-09-17T19:30:31.523+0200] {subprocess.py:93} INFO - [0m17:30:31  Up to date!
[2025-09-17T19:30:33.304+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-17T19:30:33.306+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-17T19:30:33.373+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-17T17:15:00+00:00, execution_date=20250917T171500, start_date=20250917T173006, end_date=20250917T173033
[2025-09-17T19:30:33.464+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-17T19:30:33.509+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-17T19:30:33.512+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
