[2025-09-17T17:45:03.645+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-17T17:45:03.695+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T15:30:00+00:00 [queued]>
[2025-09-17T17:45:03.707+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T15:30:00+00:00 [queued]>
[2025-09-17T17:45:03.709+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-17T17:45:03.725+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-17 15:30:00+00:00
[2025-09-17T17:45:03.734+0200] {standard_task_runner.py:64} INFO - Started process 1510 to run task
[2025-09-17T17:45:03.741+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-17T15:30:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpkwb5n9r7']
[2025-09-17T17:45:03.744+0200] {standard_task_runner.py:91} INFO - Job 103: Subtask dbt_deps
[2025-09-17T17:45:03.870+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T15:30:00+00:00 [running]> on host 1621268d5064
[2025-09-17T17:45:04.352+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T15:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-17T15:30:00+00:00'
[2025-09-17T17:45:04.353+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-17T17:45:04.368+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-17T17:45:04.370+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-17T17:45:04.390+0200] {subprocess.py:86} INFO - Output:
[2025-09-17T17:45:07.009+0200] {subprocess.py:93} INFO - [0m15:45:07  Running with dbt=1.8.3
[2025-09-17T17:45:08.236+0200] {subprocess.py:93} INFO - [0m15:45:08  Installing dbt-labs/dbt_utils
[2025-09-17T17:45:12.568+0200] {subprocess.py:93} INFO - [0m15:45:12  Installed from version 1.3.1
[2025-09-17T17:45:12.571+0200] {subprocess.py:93} INFO - [0m15:45:12  Up to date!
[2025-09-17T17:45:13.748+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-17T17:45:13.750+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-17T17:45:13.803+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-17T15:30:00+00:00, execution_date=20250917T153000, start_date=20250917T154503, end_date=20250917T154513
[2025-09-17T17:45:13.846+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-17T17:45:13.866+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
