[2025-09-16T01:15:09.243+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T01:15:09.347+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T23:00:00+00:00 [queued]>
[2025-09-16T01:15:09.376+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T23:00:00+00:00 [queued]>
[2025-09-16T01:15:09.377+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-16T01:15:09.403+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-15 23:00:00+00:00
[2025-09-16T01:15:09.421+0200] {standard_task_runner.py:64} INFO - Started process 457 to run task
[2025-09-16T01:15:09.427+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-15T23:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpdczb7qgx']
[2025-09-16T01:15:09.435+0200] {standard_task_runner.py:91} INFO - Job 15: Subtask dbt_deps
[2025-09-16T01:15:09.624+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T23:00:00+00:00 [running]> on host 1621268d5064
[2025-09-16T01:15:10.303+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T23:00:00+00:00'
[2025-09-16T01:15:10.306+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T01:15:10.340+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-16T01:15:10.349+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-16T01:15:10.377+0200] {subprocess.py:86} INFO - Output:
[2025-09-16T01:15:14.838+0200] {subprocess.py:93} INFO - [0m23:15:14  Running with dbt=1.8.3
[2025-09-16T01:15:16.560+0200] {subprocess.py:93} INFO - [0m23:15:16  Installing dbt-labs/dbt_utils
[2025-09-16T01:15:23.521+0200] {subprocess.py:93} INFO - [0m23:15:23  Installed from version 1.3.1
[2025-09-16T01:15:23.523+0200] {subprocess.py:93} INFO - [0m23:15:23  Up to date!
[2025-09-16T01:15:25.104+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-16T01:15:25.106+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T01:15:25.174+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-15T23:00:00+00:00, execution_date=20250915T230000, start_date=20250915T231509, end_date=20250915T231525
[2025-09-16T01:15:25.242+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-16T01:15:25.308+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-16T01:15:25.312+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
